### ISSUE TITLE
Possibly urgent fix for your sort thingy!

### ISSUE THREAD

**Issue by dncrews** [markgardner/sort2013#1]
Hey man. Looks like you've got some private credentials there in this public repository. I'm assuming they're no longer valid, but you should probably delete it anyway...

https://github.com/markgardner/sort2013/blob/master/.env

I'm not still with FS either, but I thought you might like to help them out anyway.

**Comment by markgardner** [comment]
Your right thanks for pointing that out. I have removed it from the history. Where are you now?

**Comment by dncrews** [comment]
Vivint Solar in Lehi
